### PR TITLE
Add plugin ctx

### PR DESCRIPTION
**Pull request by joschi36**
https://github.com/postfinance/kubectl-ctx

-----

**Checklist for plugin developers:**

- [x] Read the [Plugin Naming Guide](https://github.com/GoogleContainerTools/krew/tree/master/docs/NAMING_GUIDE.md) (for new plugins)
- [x] Verify the installation from URL or a local archive works (`kubectl krew install --manifest=[...] --archive=[...]`)

### CODE REVIEW

**Comment by joschi36** [comment]
I signed it!

**Comment by ahmetb** [comment]
Unfortunately as the owner of kubectx, I think the “ctx” choice is a “name grab” per Naming Guide.

I don’t even give my own tool to put a name grab onto a first class noun like that. So please find an original name for your plugin, or wait until we implement multi-index feature (so you don’t have to submit to krew-index and you can distribute yourself).

**Comment by djboris9** [comment]
Hi @ahmetb 
I'm not the author of https://github.com/postfinance/kubectl-ctx but work with him together.
We used your kubectx and kubens but had to implement something without bash, as many of our developers use Windows without bash.

For me it makes sense that you add your kubectx to krew-index, as it is much more popular/adopted than ours.

**Comment by ahmetb** [comment]
Closing this for now. I recommend distributing it separately until we figure out how to add more index repos to krew.

**Pull request closed without merging**
