### PR TITLE
Update rbac-view v0.2.1

### PR DESCRIPTION
**Pull request by jasonrichardsmith**

### CODE REVIEW

**Comment by jasonrichardsmith** [comment]
Hi, I can resolve the conflicts on this, but I am not sure how to resolve the CLA issue.

Any input would be appreciated. Below is a link to the Makefile that is auto merging this.
https://github.com/jasonrichardsmith/rbac-view/blob/master/Makefile#L65

**Comment by ahmetb** [comment]
I think there's a  merge conflict.

**Comment by ahmetb** [comment]
@jasonrichardsmith interesting question on how to automate this.

About the merge-conflict: I think you should check out the main repo (GoogleContainerTools/krew-index) in your script, then you should add your own fork as a git-remote to push there.

About the CLA: I think your branch has 2 commits right now. One of the commits have committer ID as travisci account: https://github.com/GoogleContainerTools/krew-index/commit/7508ac3f09d69ff18bf7d9fe9d9ec20f24f661fb.patch, if you can figure out how to get rid of that, that's your answer.

TBH I recommend keeping this process manual for now to end up with fewer headaches.

**Comment by ahmetb** [comment]
Would you like to resolve conflicts manually on this one?

**Pull request closed without merging**
