### PR TITLE
Add a new plugin "service"

### PR DESCRIPTION
**Pull request by superbrothers**
This PR adds a new plugin "service". This kubectl plugin opens the Kubernetes URL(s) for the specified service in your browser.

- https://github.com/superbrothers/kubectl-service-plugin

image

### CODE REVIEW

**Comment by lbb** [comment]
I like the plugin, as this uses a Go lib for the browser support. Can it be used under Windows?

IHMO service is a too generic name. Maybe the plugin should be called `open-svc` or `browse-service`?

**Comment by superbrothers** [comment]
If it is possible, I want to continue to use this name. Because some people already use this plugin with this name. Furthermore I have to make many changes such as source code, repository name, and more.

**Comment by ahmetb** [comment]
I'm ok with this name in the index.

But, I *strongly recommend* renaming the plugin to something original. This is a personal suggestion as I think anyone searching for "kubernetes service" will not probably see this plugin at all.

An original name like "serve" or "open-svc" can perform much better. The repo doesn't look like it has a ton of popularity yet. So please consider finding a good name for the plugin in its early days –that will help you get traction as well.

**Comment by superbrothers** [comment]
> So please consider finding a good name for the plugin in **its early days** that will help you get traction as well.

You're completely right. I rename this plugin to `open-svc`, so I'll close this PR. I'll recreate a PR after renamed.

Thanks.

**Pull request closed without merging**
