### PR TITLE
add view-taints plugin

### PR DESCRIPTION
**Pull request by saniazara01**
A basic plugin for displaying the taints on nodes.
-----

**Checklist for plugin developers:**

- [x] Read the [Plugin Naming Guide](https://github.com/GoogleContainerTools/krew/tree/master/docs/NAMING_GUIDE.md) (for new plugins)
- [x] Verify the installation from URL or a local archive works (`kubectl krew install --manifest=[...] --archive=[...]`)

### CODE REVIEW

**Comment by ahmetb** [comment]
Installation is failing at the moment. See travis check. 

Also can you link to the script in your repo? I can’t seem to find the .sh in your repo.

**Comment by saniazara01** [comment]
> Installation is failing at the moment. See travis check.
> 
> Also can you link to the script in your repo? I can’t seem to find the .sh in your repo.

Just added the script to the repo, it was under release earlier. 
https://github.com/saniazara01/kubectl-view-taints/blob/master/view-taints.sh

**Comment by saniazara01** [comment]
And regarding the travis failure, I uploaded file to repo after I pushed the yaml here so I think it couldn't find the tar then. :(

**Comment by ahmetb** [comment]
Regardless, you have to fix that. :)

I am not sure if this plugin adds a real value* so we might hold off on this until we establish some guidelines. You're not supposed to do releases without code available.

*: it's a very simple bash script that calls into kubectl.

**Comment by ahmetb** [comment]
No problem, happy to host other plugins you'd write!

**Pull request closed without merging**
